# Generated by Django 5.0.6 on 2024-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('genre', models.CharField(max_length=1)),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=30)),
                ('businessName', models.CharField(max_length=100)),
                ('legalForm', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ambassadeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('pays', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('raison', models.CharField(max_length=255)),
                ('profil', models.ImageField(upload_to='ambassadeurs/')),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook', models.CharField(blank=True, max_length=30, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=30, null=True)),
                ('youtube', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_donateur', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('methode_de_paiement', models.CharField(max_length=50)),
                ('anonym', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=100)),
                ('cible', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('stories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('domaine', models.CharField(max_length=50)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date_de_fin', models.DateField()),
                ('domaine_intervention', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
