# Generated by Django 5.0.6 on 2024-06-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
