# Generated by Django 5.0.6 on 2024-07-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherant',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambassadeur',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='histoire',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
