# Generated by Django 5.0.6 on 2024-07-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0003_adherant_actif_ambassadeur_actif_histoire_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='realisation',
            name='fond_collecter',
            field=models.IntegerField(default=0),
        ),
    ]
