# Generated by Django 5.0.6 on 2024-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0004_contact_realisation_fond_collecter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetAvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('budget_souhaite', models.IntegerField(default=0)),
                ('budget_actuelle', models.IntegerField(default=0)),
            ],
        ),
    ]
