# Generated by Django 5.0.6 on 2024-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0005_projetavenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetavenir',
            name='image',
            field=models.ImageField(null=True, upload_to='projet/'),
        ),
    ]
