# Generated by Django 5.0.6 on 2024-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0006_projetavenir_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetavenir',
            name='image',
            field=models.ImageField(null=True, upload_to='static/projet/'),
        ),
    ]
