# Generated by Django 5.0.6 on 2024-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0007_alter_projetavenir_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(null=True, upload_to='static/event/'),
        ),
    ]
