# Generated by Django 5.0.6 on 2024-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0008_evenement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='realisation',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
