# Generated by Django 5.0.6 on 2024-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0009_equipe_alter_realisation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='profil',
            field=models.ImageField(null=True, upload_to='static/equipe/'),
        ),
    ]
