# Generated by Django 5.0.6 on 2024-07-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0010_equipe_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='image',
            field=models.ImageField(null=True, upload_to='static/realisation/'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
