# Generated by Django 5.0.6 on 2024-07-24 11:12

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foundation', '0011_realisation_image_alter_realisation_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadeur',
            name='profil',
            field=imagekit.models.fields.ProcessedImageField(upload_to='ambassadeurs/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='profil',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='static/equipe/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='static/event/'),
        ),
        migrations.AlterField(
            model_name='projetavenir',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='static/projet/'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='static/realisation/'),
        ),
    ]
