# Generated by Django 5.0.6 on 2024-07-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenDePaiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_paiement', models.CharField(choices=[('CARTE', 'Carte Bancaire'), ('ORANGE_MONEY', 'Orange Money'), ('PAYPAL', 'PayPal')], max_length=20)),
                ('destinataire', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
