# Generated by Django 5.0.6 on 2024-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyendepaiement',
            name='image',
            field=models.ImageField(null=True, upload_to='static/moyendePaiement/'),
        ),
    ]
