# Generated by Django 5.0.6 on 2024-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_moyendepaiement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyendepaiement',
            name='type_paiement',
            field=models.CharField(choices=[('CARTE', 'Carte Bancaire'), ('ORANGE_MONEY', 'Orange Money'), ('M_PESA', 'M_pesa'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
    ]
