# Generated by Django 5.0.6 on 2024-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_alter_moyendepaiement_type_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('decouverte', models.CharField(max_length=50)),
            ],
        ),
    ]
