# Generated by Django 5.0.6 on 2024-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_donateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateur',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
