# Generated by Django 5.0.6 on 2024-07-11 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_donateur_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 7, 59, 46, 18442, tzinfo=datetime.timezone.utc)),
        ),
    ]
