# Generated by Django 5.0.6 on 2024-07-11 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0007_alter_donateur_date_alter_donateur_decouverte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateur',
            name='code_transfert',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donateur',
            name='nom_du_destinataire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 13, 52, 24, 427, tzinfo=datetime.timezone.utc)),
        ),
    ]
