# Generated by Django 5.0.6 on 2024-07-15 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0008_donateur_code_transfert_donateur_nom_du_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 8, 15, 58, 50679, tzinfo=datetime.timezone.utc)),
        ),
    ]
