# Generated by Django 5.0.6 on 2024-07-24 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0009_alter_donateur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 11, 12, 5, 542103, tzinfo=datetime.timezone.utc)),
        ),
    ]
