# Generated by Django 5.0.6 on 2025-04-28 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0013_alter_donateur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 9, 35, 14, 686144, tzinfo=datetime.timezone.utc)),
        ),
    ]
