# Generated by Django 5.0.6 on 2025-04-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0015_alter_donateur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 10, 1, 50, 9759, tzinfo=datetime.timezone.utc)),
        ),
    ]
